### ISSUE TITLE
Please AI VS AI mode support

### ISSUE THREAD

**Issue by himrock922** [a544jh/panel-pop#11]
Hi everyone.
First, Thanks for this panel-pop release!

I'm web developer, not game(also game ai )developer.
But, I want learning about game ai.
Therefore, I'm customize that ai based on panel-pop ai.

My hope is support AI vs AI mode on panel-pop.
Hereby, that can new ai performance compare with existing AI.

attach file is AI vs AI mode sample gif
![ai_vs_ai](https://user-images.githubusercontent.com/4998536/65785225-dd8b2480-e18e-11e9-9a01-555d6a9d5f46.gif)

Regards.

**Comment by a544jh** [comment]
It's already kind of implemented. If you wait at the title screen it will play a demo, which is the AI playing against itself. It's set up in the `DemoGameState` class. If you want to implement your own AI, you can inherit the `BoardController` class.

**Comment by himrock922** [comment]
@a544jh 

Sorry, This issue close.
