### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tobyhinloopen** [a544jh/panel-pop#3]
What's the license for this project? Can I use some of the code in a commercial project?

**Comment by a544jh** [comment]
I haven't released the code under any specific license yet, but I have thought of MIT or GPL. What part of the code are you thinking of using, and in what kind of project?

**Comment by tobyhinloopen** [comment]
I want to build a panel-de-pon like game combined with a dynamic piano soundtrack where you have to clear blocks to play notes. COOP or VS is done by using piano compositions that require multiple piano players working together or playing in some kind of "piano battle" where each player is required to take turns in playing something cool. It is mostly an idea I want to play with together with a friend that is well-capable of actually playing the piano. I find it hard to explain it properly, especially in English, which is why I want to build a playable prototype to see if it is fun to play and if others agree.

That is where your code might come in. I also have my own working code-base written in about 2000 lines of C-code (incl. chains, combos, garbage blocks, etc) but yours seems a bit more stable & readable (my C code is a mess hah) and has a working AI.

It is mostly about creating a prototype for now, but I don't want to build upon code I know I cannot redistribute in the future. I'm not a professional game developer, but I might want to release something on Steam/iOS/Android/OSX Appstore/whatever in the future if I (and others) like the prototype and decide to continue.

**Comment by a544jh** [comment]
I licensed the code under MIT, so feel free to use the code under those terms.
